### ISSUE TITLE
Can we please get a "raw" loader?

### ISSUE THREAD

**Issue by otheus** [tenderlove/psych#286]
There are times when we need to load a YAML file but for various reasons, we do _not want or care about the serialization/native dataclass conversions_. We want to load the data in as a hash-tree object, as if the object classifier were not there. 

Now it seems to me based on the [long discussion related to the `safe_load` method](https://github.com/tenderlove/psych/issues/119), that `safe_load` does not, in fact, do what is requested here. It seems to me that several sane voices were a bit shuoted down in that discussion. But whatever.

What is needed is essentially to load YAML files as if they were dumb JSON files. As if the following code were implemented before the `#load`

```ruby
yamltext = File.read("somefile","r")
yamltext.sub!(/^--- \!.*$/,'---')
purehash = YAML.load(yamltext)
```

Given the following YAML:
```yaml
--- !ruby/object:Some::Custom::Type::User::Has::No::Gem::For
 node: "string"
 array:
  - "string"
  - unquoted text
  - "12.5"
  - 12.5
  - subarray:
      option: true
      nottrue: "false"

```

We get back from #load:

```
{"node"=>"string", "array"=>["string", "unquoted text", "12.5", 12.5, {"subarray"=>{"option"=>true, "nottrue"=>"false"}}]}
```

I propose an implementation that is cleaner, that uses `YAML.load()` but based on the parser-personality. The personalities might be a kind of a "raw" mode and "native-object" mode. Raw mode only sees Hash, Array, String. Native-object mode also sees numeric, boolean (and..?)

```ruby
Psych.set_parse_mode(:native_object_conversion)
purehash=YAML.load(yamltext)
```

Produces the inspected output, above. Whereas:

```ruby
Psych.set_parse_mode(:no_object_conversion)
purehash=YAML.load(yamltext)
```

produces (subtly different):

```
{"node"=>"string", "array"=>["string", "unquoted text", "12.5", "12.5", {"subarray"=>{"option"=>"true", "nottrue"=>"false"}}]}
```
